name: CI (check linter && check test)

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci

      - if: matrix.task == 'lint'
        run: npm run lint

      - if: matrix.task == 'test'
        run: npm run test
