name: Release Production
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version to release"
      issue-number:
        type: number
        required: true
        description: "Release Issue number id"

jobs:
  run_docker:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.LOGIN }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo ${{ secrets.YANDEX_TOKEN }} | docker login --username oauth --password-stdin cr.yandex

            docker pull cr.yandex/${{vars.CR_ID}}/app:${{ inputs.version }}_latest
            docker kill $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker run -d --restart unless-stopped -p 3000:3000 cr.yandex/${{vars.CR_ID}}/app:${{ inputs.version }}_latest

  add_issue_comment:
    needs: [run_docker]
    runs-on: ubuntu-latest
    steps:
      - name: Put current date into a variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{inputs.issue-number}}
          body: |
            **Prod**:
            - Date: ${{env.NOW}}
            - Author: ${{ github.triggering_actor }}
