name: Release

on:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, test]
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - if: matrix.task == 'lint'
        run: npm run lint

      - if: matrix.task == 'test'
        run: npm run test
  release:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "RELEASE_VERSION=${{ github.run_number }}" >> $GITHUB_ENV
          shell: bash

      - run: |
          git checkout -b release/$RELEASE_VERSION
          git push origin release/$RELEASE_VERSION

      - run: |
          docker build -t cr.yandex/${{ vars.CR_ID }}/app:$RELEASE_VERSION -t cr.yandex/${{ vars.CR_ID }}/app:$RELEASE_VERSION_latest .
